### ISSUE TITLE
Add Shift keys to Unshaky

### ISSUE THREAD

**Issue by balazspekarcc** [aahung/Unshaky#50] opened 2019-04-02 12:28 UTC
In the configuration window there is no option to add Shift keys.
On my MacBook Pro the left shift is "broken". 
It would be nice to have this listed along with the other keys as well.

**Comment by aahung** [comment] 2019-04-02 15:58
It is a long-overdue feature... I hardly see it as a priority, since these keys, not like keys such as `space`, does not produce annoying extra inputs when double pressed. Anyway I will implement it when I have time, to make Unshaky feel "complete." 

Just curious, how does a bouncing "shift" key affect the keyboard functionality?

duplicate of #8

**Comment by aahung** [comment] 2019-04-02 16:10
moving the discussion to #8

**Closed by aahung** 2019-04-02 16:10 UTC
Labels: duplicate, enhancement
