### ISSUE TITLE
"power" becomes "powoer", seemingly delayed second press

### ISSUE THREAD

**Issue by cperezabo** [aahung/Unshaky#29] opened 2019-02-10 21:08 UTC
Hi, I have progressively increased the delay time starting from 40ms and I cannot go further than 60ms because I almost cannot type "google". 

The problem I am having right now is that, for example, I am typing "power", so I press "p" "o" "w" and an additional "o" appears leaving a "powoer" in the screen when I end up typing.

Anything I can try? sadly in my country there is no official Apple stores, and partners can take your laptop for months before telling you that replacements are not arriving because of import problems

**Comment by aahung** [comment] 2019-02-10 21:11
Can you open the debug windows, reproducing the problem and post the debug log here so I can look into it.

**Comment by cperezabo** [comment] 2019-02-10 21:13
I am trying to reproduce it but it is not happening now, as you already know it is very random! Sometimes nothing happens and sometimes it start failing repeatedly. As soon as it happens again I will record with the debug window and post it here!

**Comment by cperezabo** [comment] 2019-02-10 21:15
Oh and sorry for the title thing, I was so concerned about the issue itself I forgot finish writing the title

**Comment by aahung** [comment] 2019-02-10 21:19
Sure, let's see whether it is some issue can be fixed by software. Hope it is just you typing very fast :-). Otherwise, I kind of worry whether it is kind of next level hardware issue the bounce no long be restricted within a very short time, and making it hard to distinguish from normal key presses. 

@cperezabo no worry, the title thing is totally fine.

**Comment by cperezabo** [comment] 2019-02-10 21:20
While I was writing the word "finish" it happened with the "n" and I wrote "fininsh", luckily I had the debugger opened
<img width="304" alt="screen shot 2019-02-10 at 18 16 05" src="https://user-images.githubusercontent.com/3604722/52539753-77b56e00-2d60-11e9-8726-14ebe207ebe4.png">

**Comment by aahung** [comment] 2019-02-10 21:29
Kind of weird, it does not seem to be typing "finish"

<img width="304" alt="52539753-77b56e00-2d60-11e9-8726-14ebe207ebe4" src="https://user-images.githubusercontent.com/3804518/52539873-e205e880-2d37-11e9-8004-2f50b2371454.png">

**Comment by cperezabo** [comment] 2019-02-13 17:53
I have noticed debugger is not logging keys with 0ms delay, that's why you can't see the full "finish" word. Is this partial logging a by-design behavior or a bug? It would be easier to debug if you add a column with the value of the pressed key so you can graphically find the word. Just an idea.

**Comment by aahung** [comment] 2019-02-13 18:47
Oh I forgot that sorry. It was implemented as it is by-design but now I think it makes more sense to show all keys.

I can tell from the log, the last two N presses have ~110ms in between, which is longer than the delay. The keyup of 1st N and keydown of 2nd N are very close thought, and it might be something we can use to recognize it.

As for showing the word instead of the code, I should definitely implement it, thanks for the suggestion.

**Comment by aahung** [comment] 2019-02-13 19:00
If you set the delay to 50ms, the last "N" should have been dismissed. Can you try to set the delay of "N" to a very large value (e.g., 900ms) and press it quickly for several times and see whether some "N" are labelled dismissed? Maybe something is wrong with the event interception?

**Comment by cperezabo** [comment] 2019-02-20 12:15
I setup 900ms for R key and It was dismissed just the second time I pressed it.
<img width="432" alt="screen shot 2019-02-20 at 09 13 56" src="https://user-images.githubusercontent.com/3604722/53091166-014b0580-34f0-11e9-9505-c00bb7ee1fc4.png">

**Comment by cperezabo** [comment] 2019-02-20 12:18
Now quickly
<img width="400" alt="screen shot 2019-02-20 at 09 17 53" src="https://user-images.githubusercontent.com/3604722/53091341-79b1c680-34f0-11e9-8a3f-3820600bfd8c.png">

**Comment by cperezabo** [comment] 2019-02-20 12:22
When I uploaded the last image I see something with my developer's eyes. I tried again with with a large debugger window and after pessing R quickly...... Is it a pattern?
<img width="407" alt="screen shot 2019-02-20 at 09 20 23" src="https://user-images.githubusercontent.com/3604722/53091481-cbf2e780-34f0-11e9-8ab8-aa2b21c2ee54.png">

**Comment by cperezabo** [comment] 2019-02-20 12:33
Now with pressing "o" and "r" at a fixed pace
<img width="398" alt="screen shot 2019-02-20 at 09 30 00" src="https://user-images.githubusercontent.com/3604722/53092067-83d4c480-34f2-11e9-9365-eb7e971e7f10.png">

**Comment by cperezabo** [comment] 2019-02-20 12:36
Now pressing just "R" quickly, and then less quickly, and less quickly
<img width="404" alt="screen shot 2019-02-20 at 09 35 50" src="https://user-images.githubusercontent.com/3604722/53092238-fe9ddf80-34f2-11e9-8381-0f3820ab0413.png">

**Comment by aahung** [comment] 2019-02-20 18:47
It seems to work as expected for the 5 screenshots you just uploaded... My guess is maybe the delay was not effectively set previously. Can you set the delay back to normal and see if the problem still persists?

**Comment by cperezabo** [comment] 2019-02-20 22:06
It's set back to 55ms as the rest of the keys. Problem persists. I get a key repeat after having press another key, randomly of course because I'm just typing and boom.

**Comment by aahung** [comment] 2019-02-20 23:07
I am starting to wonder whether it is vibration from the press on another key causes the problem. Right now there are "n" and "o" being effected as far as I know, any other keys?

**Comment by cperezabo** [comment] 2019-02-21 14:15
No I have delay set up for [c, e, i, k, n, o, r, t, space] and happens to all of those keys, but some of them are used more often.

**Comment by aahung** [comment] 2019-02-22 04:24
Sorry I still cannot figure out what the cause is. The only option right now is to keep debug window open to generate more log, and hope we can see some patterns. 

This version of Unshaky below has key delay in the debug window, you can also build it with the latest commit.
[Unshaky_v0.3.4_internal.zip](https://github.com/aahung/Unshaky/files/2892350/Unshaky_v0.3.4_internal.zip)

**Comment by cperezabo** [comment] 2019-02-23 16:47
I was writing "Hearts on fire" and it ends up being "Hearts **ono** fire". There it is the ghost "o"
<img width="407" alt="screen shot 2019-02-23 at 13 43 19" src="https://user-images.githubusercontent.com/3604722/53289182-82fd9600-3771-11e9-8241-077a7fd5b34d.png">

**Comment by aahung** [comment] 2019-02-23 20:34
Wow, your “o” key has triple presses... I might have an idea to deal with it. Thanks for the debug info.

**Comment by aahung** [comment] 2019-02-23 21:15
@cperezabo Try [v0.4.0](
https://github.com/aahung/Unshaky/releases/tag/v0.4.0) and turn on "aggressive mode" in setting to see if it can solve your problem.

**Comment by aahung** [comment] 2019-02-23 21:17
<img width="432" alt="screen shot 2019-02-23 at 1 16 26 pm" src="https://user-images.githubusercontent.com/3804518/53291761-521b6200-376d-11e9-950f-9f244a89c1ad.png">

**Comment by aahung** [comment] 2019-02-25 06:13
@cperezabo Just wanna check how it goes?

**Comment by cperezabo** [comment] 2019-02-25 16:36
I just installed it and will be checking it

**Comment by aahung** [comment] 2019-02-25 23:05
I think this "aggressive mode" should be the default mode when it is tested enough.

**Comment by cperezabo** [comment] 2019-02-26 11:55
Yes, I think that too. I have been using it since yesterday and it works flawlessly but something happend 1% of times, I got some duplicated. I was writing "I don't know" and got "I don't kno**o**w"
<img width="405" alt="screen shot 2019-02-26 at 08 54 36" src="https://user-images.githubusercontent.com/3604722/53411061-4b2a6480-39a4-11e9-86f4-f527968bec16.png">

**Comment by cperezabo** [comment] 2019-02-26 11:58
Take a look at the first ~6, don't know what's happening. Problem is almost cancelled btw. While writing this I got another extra "o"

**Comment by cperezabo** [comment] 2019-02-26 14:54
Writing "nos" I got "noos", I hope to have marked correctly, just to help.
<img width="414" alt="screen shot 2019-02-26 at 11 52 18" src="https://user-images.githubusercontent.com/3604722/53421827-18409a80-39bd-11e9-8862-27945c89f0cc.png">

**Comment by aahung** [comment] 2019-02-26 20:26
Great to know 99% of the time it works!

From the log the abnormal bounce occurred >55ms, which is longer than what I expected, and difficult to distinguish from normal presses.  If you type fast. If it is only happening to your “o” key, try to set the delay of ‘o’ to something larger without mess up with your normal typing.

**Comment by cperezabo** [comment] 2019-02-26 20:28
<img width="512" alt="screen shot 2019-02-26 at 17 23 29" src="https://user-images.githubusercontent.com/3604722/53443934-9ae04e80-39eb-11e9-9dbc-73153541e036.png">
No writing "turno con" got "turnoo con", the crazy thing is why there is an "o" befor pressing the "n". It's like having a ghost "o" here -> "tur**o**no

**Comment by aahung** [comment] 2019-02-26 21:43
It is not before pressing the "n", instead it is before **releasing** the "n" which is fine.
The issue here is (see the screenshot) for the two "o" presses, the second one is obviously unwanted but since it is ~70ms away from the first one (>55ms), Unshaky won't block it. I would suggest you to set the delay of "o" to something around "80ms."

<img width="512" alt="53443934-9ae04e80-39eb-11e9-9dbc-73153541e036" src="https://user-images.githubusercontent.com/3804518/53448305-f4388580-39cb-11e9-889e-4421dbacfbd8.png">

**Comment by cperezabo** [comment] 2019-02-27 12:28
55 is my longest delay possible because I cannot type google nor facebook. I guess I will have to live with it 😕

**Comment by aahung** [comment] 2019-02-27 17:01
I really hope it can block 100% of these, but your issue seems to be severe... and software solution might not be able to deal with it anymore...

PS: thanks for helping improve Unshaky!

**Closed by aahung** 2019-02-27 17:01 UTC
Labels: bug
