### ISSUE TITLE
App is not working after launching on login

### ISSUE THREAD

**Issue by anatoliliotych** [aahung/Unshaky#10] opened 2018-08-22 08:03 UTC
I've noticed that the app stopped working after relogin, to fix this I had to restart app.

**Comment by aahung** [comment] 2018-08-22 23:36
you mean you "Log Out [user name]..." and then log back in?

**Comment by anatoliliotych** [comment] 2018-08-23 11:11
Yes, I had to reboot laptop. And app was launched, but it didn't work.

**Comment by ChristBKK** [comment] 2018-08-27 11:04
for me i installed it but it shows still 0 dismissed keys?  I did also the settings in the accessability

**Comment by anatoliliotych** [comment] 2018-08-28 06:12
@ChristBKK did you try to set value other than 0?

**Comment by ChristBKK** [comment] 2018-08-28 08:57
thanks thats a good idea :D now I got it I have to set the MS in the Settings.  I did that now and testing

**Comment by ChristBKK** [comment] 2018-08-28 11:07
works great so far keep up the good work! Really helps

**Comment by ChristBKK** [comment] 2018-08-28 11:29
@aahung  just to let you know this is still needed :D my new Macbook Pro 2018 has this bug. So it's not resolved with a new keyboard perse.

**Comment by aahung** [comment] 2018-08-28 11:49
Hi Anatoli, the issue is odd, I will look into it after traveling back.

**Comment by aahung** [comment] 2018-08-28 13:39
@ChristBKK Oh really? I thought the extra membrane makes a difference.

**Comment by ChristBKK** [comment] 2018-09-10 07:52
@aahung   nope.. it is still there. I work on the newest Macbook Pro.  So you app is a lifesaver.   Thanks for your hard work. I recommend it to my friends when they have the same problem.

Please keep updating it from time to time if needed.

**Comment by aahung** [comment] 2018-09-10 17:48
@ChristBKK It is unfortunate they did not fix the issue once for all.

**Comment by aahung** [comment] 2018-09-10 17:54
@anatoliliotych I tried to log out and log in back, with Unshaky.app in "login items", and with "reopen windows when logging back in" off, the Unshaky started and worked. 

Can you give more details about the info and configurations of your system such as:

- OS version
- how you log out?
- does Unshaky icon shows up in the menu bar after you log back in?
- anything showing up in the debug window?

**Comment by anatoliliotych** [comment] 2018-09-10 17:56
So as I remember my laptop switched after 0% of battery, and after I charged it, the app was in the menu bar, debug was clear. OS was up to date.

**Comment by aahung** [comment] 2018-09-10 17:57
Do you also encounter such issue when you normally log out and log back in?

**Comment by anatoliliotych** [comment] 2018-09-10 17:58
Normal workflow - works fine.

**Comment by aahung** [comment] 2018-09-10 18:04
I guess it has something to do with how macOS handles "recovery from battery drained." 

Unshaky inserts an event tap in the user session so that it works as long as the user stays log in. When  the battery dies and then charged, the user session is not ended, but the event tap is somehow missing. 

Consider it has this issue under such a rare and abnormal situation, I will not dig the cause too deep since forcing my battery die is kind of 😢, hope you don't mind.

**Closed by aahung** 2018-09-10 18:04 UTC
Labels: bug

**Comment by anatoliliotych** [comment] 2018-09-10 18:06
Sure no problem! I've just noticed and decided to report! But as you've said - not a big deal! Thanks!

**Comment by aahung** [comment] 2018-09-10 18:08
@anatoliliotych I really appreciate you reported that. Next time similar issues reported I will know what to look for.
