### ISSUE TITLE
Please, add cmd key in list!

### ISSUE THREAD

**Issue by TorlopovAndrey** [aahung/Unshaky#134] opened 2019-11-05 10:12 UTC
**Is your feature request related to a problem? Please describe.**
I have a problem with left cmd button. Can you add this key in list?

**Comment by hazarek** [comment] 2019-11-06 23:13
@TorlopovAndrey duplicate of https://github.com/aahung/Unshaky/issues/8
I think you should close the title

**Closed** 2019-12-15 08:50 UTC
Labels: duplicate
