### ISSUE TITLE
Extra "Input Monitoring" Permission required in Catalina 10.15.7

### ISSUE THREAD

**Issue by scottlaurent** [aahung/Unshaky#172] opened 2020-12-10 02:30 UTC
**Describe the bug**
On approximately 50% of certain keys pressed (in my case E and I) -- I've set the ms to 1000+ and there is zero effect. This just started on my recent update to Catalina 10.15.7

**Desktop (please complete the following information):**
 -  Catalina 10.15.7

**Additional context**
I've tested using Unshaky .60 and 0.63, and have tested the workarounds posted for Catalina 10.15.6 with no success

**Comment by aahung** [comment] 2020-12-12 00:28
do you have external keyboard turned on? How about delay like 500ms (I remember someone mentioning 1000+ has the same effect as 0)

**Comment by Dhilan001** [comment] 2020-12-13 07:26
> **Describe the bug**
> On approximately 50% of certain keys pressed (in my case E and I) -- I've set the ms to 1000+ and there is zero effect. This just started on my recent update to Catalina 10.15.7
> 
> **Desktop (please complete the following information):**
> 
> * Catalina 10.15.7
> 
> **Additional context**
> I've tested using Unshaky .60 and 0.63, and have tested the workarounds posted for Catalina 10.15.6 with no success

This happened to me also, I fixed by enabling aggressive mode and setting delay to 40ms. This might work for you try it out and lmk

**Comment by simmac** [comment] 2021-01-03 20:15
I have the same problem. Sometimes (probably directly after a reboot) it works until the next sleep. I tried enabling aggressive mode, didn't help :/

**Comment by aahung** [comment] 2021-01-07 20:55
> I have the same problem. Sometimes (probably directly after a reboot) it works until the next sleep. I tried enabling aggressive mode, didn't help :/

what's in the debug window

**Comment by simmac** [comment] 2021-01-07 21:00
> what's in the debug window

When it's working correctly, every keypress appears in the debug window. When it doesn't work, only keypresses on special keys (eg cmd or alt) appear.

**Comment by aahung** [comment] 2021-01-07 21:18
Only modifier keys show up? That's odd. Can you paste a small snippet of log here so I can have something more concrete? 

Also, what's your configuration (the checkboxes below delay config)

**Comment by simmac** [comment] 2021-01-07 21:34
My machine is currently at Apple service (for keyboard replacement, so I guess this fixes the issue for me :P), but I will get back to you when I have my machine again (feel free to remind me when I don't get back to you within two weeks)

Regarding the configuration, I left it at default values (I believe that's everything unchecked?) apart from aggressive mode, which didn't change the behaviour at all (I observed it with and without aggressive mode)

**Comment by aahung** [comment] 2021-01-10 23:37
There is another bug report on 10.15.7 #176. I managed to test Unshaky on a 10.15.7 macbook and it works fine. Cannot reproduce it now.

**Comment by duselbaer** [comment] 2021-01-25 21:46
Same here, Unshaky works fine after rebooting the machine. But after a while (stand-by's) included - it stops working. The debug window only shows some special keys. Attached is the content of the log window after typing this comment.

```
1611611051.289417 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611611051.668953 Key( 59| 56|       Unknown|         0| 40) E(12)
1611611056.950138 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611611057.210571 Key( 59| 56|       Unknown|         0| 40) E(12)
1611611064.883992 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611611065.444023 Key( 59| 56|       Unknown|         0| 40) E(12)
1611611068.866654 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611611069.371118 Key( 59| 56|       Unknown|         0| 40) E(12)
1611611081.720370 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611611081.968347 Key( 59| 56|       Unknown|         0| 40) E(12)
1611611085.157342 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611611085.405356 Key( 59| 56|       Unknown|         0| 40) E(12)
1611611085.524058 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611611085.832650 Key( 59| 56|       Unknown|         0| 40) E(12)
1611611086.272176 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611611086.680566 Key( 59| 56|       Unknown|         0| 40) E(12)
1611611094.669889 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611611095.005575 Key( 59| 56|       Unknown|         0| 40) E(12)
1611611110.254395 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611611110.810675 Key( 59| 56|       Unknown|         0| 40) E(12)
1611611111.558348 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611611111.790121 Key( 59| 56|       Unknown|         0| 40) E(12)
1611611130.314768 Key( 59| 55|       Unknown|   1048576| 40) E(12)
1611611130.670779 Key( 59| 55|       Unknown|         0| 40) E(12)
```

Can I support somehow in debugging this issue?

**Comment by duselbaer** [comment] 2021-01-26 14:43
And this is what it looks like after reboot - typing "Hello World ..."
`

1611672135.102851 Key( 59| 55|       Unknown|   1048576| 40) E(12)
1611672135.243381 Key( 59| 48|           Tab|   1048576| 40) E(10)
1611672135.403145 Key( 59| 48|           Tab|   1048576| 40) E(11)
1611672136.194595 Key( 59| 55|       Unknown|         0| 40) E(12)
1611672136.449846 Key(198|  0|             A|         0| 40) E(12)
1611672141.238592 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611672142.846658 Key( 59|  4|             H|    131072| 40) E(10)
1611672142.938518 Key( 59|  4|             H|    131072| 40) E(11)
1611672142.950529 Key( 59| 56|       Unknown|         0| 40) E(12)
1611672143.039209 Key( 59| 14|             E|         0| 40) E(10)
1611672143.143625 Key( 59| 14|             E|         0| 40) E(11)
1611672143.181909 Key( 59| 37|             L|         0| 40) E(10)
1611672143.270709 Key( 59| 37|             L|         0| 40) E(11)
1611672143.321218 Key( 59| 37|             L|         0| 40) E(10)
1611672143.398481 Key( 59| 37|             L|         0| 40) E(11)
1611672143.525960 Key( 59| 31|             O|         0| 40) E(10)
1611672143.628567 Key( 59| 31|             O|         0| 40) E(11)
1611672144.480587 Key( 59| 49|         Space|         0| 40) E(10)
1611672144.576930 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611672144.616323 Key( 59| 49|         Space|    131072| 40) E(11)
1611672144.712487 Key( 59| 13|             W|    131072| 40) E(10)
1611672144.768675 Key( 59| 56|       Unknown|         0| 40) E(12)
1611672144.824488 Key( 59| 13|             W|         0| 40) E(11)
1611672144.842026 Key( 59| 31|             O|         0| 40) E(10)
1611672144.930599 Key( 59| 15|             R|         0| 40) E(10)
1611672144.950674 Key( 59| 31|             O|         0| 40) E(11)
1611672145.046280 Key( 59| 15|             R|         0| 40) E(11)
1611672145.112398 Key( 59| 37|             L|         0| 40) E(10)
1611672145.232691 Key( 59| 37|             L|         0| 40) E(11)
1611672145.509644 Key( 59|  2|             D|         0| 40) E(10)
1611672145.666630 Key( 59|  2|             D|         0| 40) E(11)
1611672146.015860 Key( 59| 49|         Space|         0| 40) E(10)
1611672146.111667 Key( 59| 49|         Space|         0| 40) E(11)
1611672146.141974 Key( 59| 44|       Slash /|         0| 40) E(10)
1611672146.237355 Key( 59| 49|         Space|         0| 40) E(10)
1611672146.297391 Key( 59| 44|       Slash /|         0| 40) E(11)
1611672146.385302 Key( 59| 49|         Space|         0| 40) E(11)
1611672147.338010 Key( 59|  2|             D|         0| 40) E(10)
1611672147.430621 Key( 59| 34|             I|         0| 40) E(10)
1611672147.469951 Key( 59|  2|             D|         0| 40) E(11)
1611672147.543503 Key( 59| 14|             E|         0| 40) E(10)
1611672147.553706 Key( 59| 34|             I|         0| 40) E(11)
1611672147.618422 Key( 59| 14|             E|         0| 40) E(11)
1611672147.728097 Key( 59|  1|             S|         0| 40) E(10)
1611672147.800210 Key( 59| 49|         Space|         0| 40) E(10)
1611672147.819832 Key( 59|  1|             S|         0| 40) E(11)
1611672147.904707 Key( 59| 49|         Space|         0| 40) E(11)
1611672147.949213 Key( 59| 34|             I|         0| 40) E(10)
1611672148.085804 Key( 59| 34|             I|         0| 40) E(11)
1611672148.139374 Key( 59|  1|             S|         0| 40) E(10)
1611672148.210803 Key( 59| 17|             T|         0| 40) E(10)
1611672148.267572 Key( 59|  1|             S|         0| 40) E(11)
1611672148.299697 Key( 59| 49|         Space|         0| 40) E(10)
1611672148.335017 Key( 59| 17|             T|         0| 40) E(11)
1611672148.442961 Key( 59| 49|         Space|         0| 40) E(11)
1611672148.481666 Key( 59| 14|             E|         0| 40) E(10)
1611672148.570349 Key( 59| 14|             E|         0| 40) E(11)
1611672148.579787 Key( 59| 34|             I|         0| 40) E(10)
1611672148.658442 Key( 59| 34|             I|         0| 40) E(11)
1611672148.707117 Key( 59| 45|             N|         0| 40) E(10)
1611672148.726795 Key( 59| 49|         Space|         0| 40) E(10)
1611672148.754996 Key( 59| 45|             N|         0| 40) E(11)
1611672148.862798 Key( 59| 56|       Unknown|    131072| 40) E(12)
1611672148.919143 Key( 59| 49|         Space|    131072| 40) E(11)
1611672149.019366 Key( 59| 17|             T|    131072| 40) E(10)
1611672149.127539 Key( 59| 56|       Unknown|         0| 40) E(12)
1611672149.167563 Key( 59| 17|             T|         0| 40) E(11)
1611672149.223041 Key( 59| 14|             E|         0| 40) E(10)
1611672149.311479 Key( 59| 14|             E|         0| 40) E(11)
1611672149.441357 Key( 59|  1|             S|         0| 40) E(10)
1611672149.484736 Key( 59| 17|             T|         0| 40) E(10)
1611672149.549119 Key( 59|  1|             S|         0| 40) E(11)
1611672149.589675 Key( 59| 17|             T|         0| 40) E(11)
1611672149.677298 Key( 59| 47|      Period .|         0| 40) E(10)
1611672149.761400 Key( 59| 47|      Period .|         0| 40) E(11)`

**Comment by cdce8p** [comment] 2021-02-05 21:14
Same here.

@aahung I noticed that even with `Catalina` there is the `Input Monitoring` section inside `Security & Privacy` -> `Privacy`. It appears as though it has been recently added, since I haven't noticed it before. I can't add Unshaky to it if that would be required however.

**Comment by aahung** [comment] 2021-02-08 08:09
Interesting. I never managed to reproduce this. Do you have other apps that might modify keyboard events such as karabiner?

**Comment by aahung** [comment] 2021-02-08 08:10
> Same here.
> 
> 
> 
> @aahung I noticed that even with `Catalina` there is the `Input Monitoring` section inside `Security & Privacy` -> `Privacy`. It appears as though it has been recently added, since I haven't noticed it before. I can't add Unshaky to it if that would be required however.

What do you mean "can't add Unshaky to it?" Is that preference pane not accessible?

**Comment by cdce8p** [comment] 2021-02-08 11:51
> Do you have other apps that might modify keyboard events such as karabiner?

No

> What do you mean "can't add Unshaky to it?" Is that preference pane not accessible?

I could only add Unshaky to the `Accessibility` tab. In the `Input Monitoring` tab I only see a message that no apps have requested this permission. That was a surprise to me since the readme states that you should add it there too, [Readme](https://github.com/aahung/Unshaky#grant-accessibility-permission). The App itself  starts normally though without complains. If I remove the `Accessibility` permission, it wouldn't even start.

<img width="700" alt="Screen Shot 2021-02-08 at 12 39 40" src="https://user-images.githubusercontent.com/30130371/107215265-61078780-6a0b-11eb-9859-0224cfa0f40d.png">

**Comment by jwaddle** [comment] 2021-03-01 23:26
In Catalina 10.15.7, I have the same issue as cdce8p. I can add and enable Unshaky in the Accessibility tab, but when I try the "Input Monitoring" tab, I get the same "Apps that have requested access to monitor input..." with no way to add or enable anything.

**Comment by aahung** [comment] 2021-03-02 00:26
@cdce8p and @jwaddle, looks like this is a known issue in macOS. https://apple.stackexchange.com/questions/379452/cannot-add-new-apps-to-mac-catalina-input-monitoring-on-security-privacy

> It looks like there is no way to add new app if no other app asked for this permision - there is no list with +/- buttons.

I think Unshaky needs to ask this permission explicitly in next version, but before that, install some other app that requests input monitor could be a workaround. Some known apps that might request such permission:

- logitich option 
- discord

**Comment by jwaddle** [comment] 2021-03-02 01:08
Thank you, that is exactly what I ended up doing. First I tried the ColorSnapper2 app, but it appeared to have the same issue re: never asking for Input Monitoring. Next I tried something called Cheat Sheet, and it worked well! After it was there populating the list, I was able to add Unshaky with the + button in Input Monitoring.  4 shaky keypresses blocked in the last 5 minutes, thanks.

**Comment by aahung** [comment] 2021-03-02 01:13
I did some testing and found only 10.15.7 seems require input monitoring to be turned on. I tested it on big sur (11.2.2) and Unshaky works without input monitoring. I think it is a bug in 10.15.7, therefore, closing this issue for now.

**Closed by aahung** 2021-03-02 01:13 UTC

**Comment by aahung** [comment] 2021-03-02 01:16
BTW, I tried to let Unshaky to request input monitoring, however, I found the only way to request it is to not to request Accessibility permission at the same time, which is not very feasible. 

```swift
IOHIDRequestAccess(kIOHIDRequestTypeListenEvent) -> request input monitor, but Unshaky won't work
IOHIDRequestAccess(kIOHIDRequestTypePostEvent) -> request accessibility, Unshaky work in big sur, but may not be adequate in 10.15.7
```

**Comment by cdce8p** [comment] 2021-03-02 01:27
I understand the limitation. Thanks for taking the time to investigate it.

**Comment by AndreaCallia** [comment] 2021-11-13 12:30
> Thank you, that is exactly what I ended up doing. First I tried the ColorSnapper2 app, but it appeared to have the same issue re: never asking for Input Monitoring. Next I tried something called Cheat Sheet, and it worked well! After it was there populating the list, I was able to add Unshaky with the + button in Input Monitoring. 4 shaky keypresses blocked in the last 5 minutes, thanks.

Thanks for this! Where did you get this Cheat Sheet app? When I google "Cheat Sheet app macos" I get completely unrelated results...
