### ISSUE TITLE
Doesn't work at all on Catalina 10.15.6 (Workaround Available, need Input Monitoring permission)

### ISSUE THREAD

**Issue by Ryanauger95** [aahung/Unshaky#166] opened 2020-10-01 18:41 UTC
**Describe the bug**
Doesn't work at all on Catalina 

**To Reproduce**
1. Set any/all key delays to 999ms, theen taap a keey twice. I'm not deleting those eduplicates, becausee it shows that unshaky is not working.

**Expected behavior**
This shouldn't be happening at all. The keys shouldnt be duplicated.

**Desktop (please complete the following information):**
 - macOS version: 10.15.6

**Comment by aahung** [comment] 2020-10-02 09:14
confirming the issue on 10.15.6 with error in `Console.app`:

```
{ID: com.nestederror.Unshaky, PID[62421], auid: 503, euid: 503, binary path: '/Applications/Unshaky.app/Contents/MacOS/Unshaky'} attempted to call TCCAccessRequest without the com.apple.private.tcc.manager.check-by-audit-token entitlement
```

**Comment by aahung** [comment] 2020-10-02 09:38
I don't know if it is due to I just renewed my Apple developer program membership. I will upload a new build to see if it can fix it

**Comment by aahung** [comment] 2020-10-02 09:51
[v0.6.1](https://github.com/aahung/Unshaky/releases/tag/v0.6.1) should fix it. Re-open if it doesn't

**Comment by aahung** [comment] 2020-10-03 03:41
I am still getting the error. Don't have a solution yet

**Comment by azk-mochi** [comment] 2020-10-11 07:28
Hello. I had the same error on Catalina and Big Sur, and recently I've got Unshaky app (v.0.6.0) work on macOS Big Sur (beta, 20A5384c).

1. Close Unshaky app
2. System Preferences -> Security & Privacy -> Privacy -> Accessibility -> delete Unshaky app -> add Unshaky app
3. System Preferences -> Security & Privacy -> Privacy -> Input Monitoring -> delete Unshaky app -> add Unshaky app
4. System Preferences -> Security & Privacy -> Privacy -> Developer Tools -> add Unshaky app
5. Relaunch Unshaky app

Hope this helps.

System Info
- Hardware: MacBook Pro 13-inch (Late 2016)
- OS: macOS Big Sur Public beta 
- Unshaky version: v0.6.0

```
$ spctl --status
assessments disabled
```
I use macOS with Gatekeeper partially disabled.. (related?)

**Comment by j-f1** [comment] 2020-10-13 19:53
Thanks, @azk-mochi! I didn’t need to do step 4 (Developer Tools). I also found that enabling the “ignore external keyboard” option stopped the app from working.

**Comment by aahung** [comment] 2020-10-14 04:25
Thank you @azk-mochi for the workaround.

I tested it on my macbook and it works. My `spctl --status` is `enabled` and I did not add Unshaky to "Developer Tools."

**Comment by dbachorz** [comment] 2020-11-05 23:10
> Hello. I had the same error on Catalina and Big Sur, and recently I've got Unshaky app (v.0.6.0) work on macOS Big Sur (beta, 20A5384c).
> 
> 1. Close Unshaky app
> 2. System Preferences -> Security & Privacy -> Privacy -> Accessibility -> delete Unshaky app -> add Unshaky app
> 3. System Preferences -> Security & Privacy -> Privacy -> Input Monitoring -> delete Unshaky app -> add Unshaky app
> 4. System Preferences -> Security & Privacy -> Privacy -> Developer Tools -> add Unshaky app
> 5. Relaunch Unshaky app
> 
> Hope this helps.
> 
> System Info
> 
> * Hardware: MacBook Pro 13-inch (Late 2016)
> * OS: macOS Big Sur Public beta
> * Unshaky version: v0.6.0
> 
> ```
> $ spctl --status
> assessments disabled
> ```
> 
> I use macOS with Gatekeeper partially disabled.. (related?)

Doesn't work for me, debounce doesn't work even if I set 2000 ms delay

**Comment by peturingi** [comment] 2020-11-12 11:02
I am unable to reproduce this bug on 10.15.7 (19H15) using Unshaky 0.6.0.

**Comment by simmac** [comment] 2020-12-30 15:45
The workaround does not work for me with 0.7.0 on macOS 10.15.7 (19H114) :(

**Comment by simmac** [comment] 2021-01-03 16:30
> The workaround does not work for me with 0.7.0 on macOS 10.15.7 (19H114) :(

nevermind, it seems to work after reinstalling the latest macOS update

**Comment by Dada40** [comment] 2021-01-05 13:11
> The workaround does not work for me with 0.7.0 on macOS 10.15.7 (19H114) :(

Had the same problem with 10.15.7 (19H114) and Unshaky 0.7.0, even though all permissions had been set in the preferences.
After some time it started working for me for whatever reason (maybe a reboot solved it?).

**Comment by desnum** [comment] 2021-02-04 01:25
With version 0.7.0, the workaround does not work for me, on macOS Catalina 10.15.7

**Comment by desnum** [comment] 2021-02-04 01:51
@simmac 

> The workaround does not work for me with 0.7.0 on macOS 10.15.7 (19H114) :(

Did you make sure that the box was checked in Accessibility? I didn't have it checked by default and when I did check it, version 0.7.0 of Unshaky worked on my macOS Catalina 10.15.7.

<img width="780" alt="unshaky checkbox" src="https://user-images.githubusercontent.com/43796228/106833242-3317f100-6661-11eb-8180-6dc802885d9b.png">

**Comment by aahung** [comment] 2021-03-02 01:18
Close this issue, the workaround is good enough.

**Closed by aahung** 2021-03-02 01:18 UTC
Labels: bug

**Comment by lakshya97** [comment] 2021-05-05 07:59
I'm unable to add it to "input monitoring" on macOS Catalina 10.15.7. This renders the app unusable. Does anyone have any suggestions?

**Comment by aahung** [comment] 2021-05-05 08:11
> I'm unable to add it to "input monitoring" on macOS Catalina 10.15.7. This renders the app unusable. Does anyone have any suggestions?

Did you check out #172?
